(async () => {
   console.log("Hello");
})().catch((error) =>{
});